### ISSUE TITLE
Url rewrite

### ISSUE THREAD

**Issue by mbenatti** [latupo/docker-magento#1]
Hi guys, i like your code but how do you resolve the urlrewrite in apache2 using this image??
Thank you!

**Comment by latupo-kl** [comment]
Hi Marcos, thanks for asking. We actually had mod_rewrite enabled in our project specific Dockerfiles. But since it makes more sense here, I now added it in this image. Should be on dockerhub now.

**Comment by mbenatti** [comment]
Great, but it seem do not work yet, i try to access http://localhost:8080/customer/account/login/ in default installation and get:
 Not Found
The requested URL /customer/account/login/ was not found on this server.

Only work with index.php. Maybe should be add additional configs in this image/debian or Magento?

**Comment by mbenatti** [comment]
Resolved
